import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import AuthStatus from "@/components/AuthStatus";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full w-full flex flex-col font-sans antialiased">
        <header className="border-b border-gray-200 px-8 py-3">
          <div className="mx-auto flex max-w-3xl items-center justify-between">
            <Link href="/" className="text-sm font-medium">
              Animation Guide
            </Link>
            <AuthStatus />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
