export {
  EMAIL_OTP_LENGTH,
  EMAIL_OTP_RESEND_COOLDOWN_MS,
  normalizeAuthEmail,
  isValidAuthEmail,
  normalizeOtpCode,
  isCompleteOtpCode,
  maskAuthEmail,
  formatCodeSentMessage,
  formatExistingCodeMessage,
  formatResendCooldownMessage,
  isEmailOtpRateLimitError,
  resolveEmailOtpSendOutcome,
  canResendEmailOtp,
  getEmailOtpResendDelayMs,
  formatEmailOtpError,
} from "./email-otp.mjs";
